# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Oeuvre',
            name='auteur',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Oeuvre',
            name='titre',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
