# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_auto_20170921_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='auteur',
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
