# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0005_auto_20170921_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='id',
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='id_zotero',
            field=models.CharField(default=0, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
