# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0006_auto_20170921_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='titre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
