# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0008_auto_20170922_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='id_zotero',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
