# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0009_auto_20170922_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='oeuvre',
            name='langue',
        ),
    ]
