# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:57
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0010_auto_20170922_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='auteur',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='repertoire.TagAuteur'),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='langue',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='repertoire.TagLang'),
        ),
    ]
