# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0012_auto_20170922_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oeuvre',
            old_name='auteur2',
            new_name='auteur',
        ),
    ]
